CREATE TABLE users (
   id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password TEXT NOT NULL,
   type VARCHAR(50) NOT NULL,
   active bool
);
